-- Dump of prompt_settings table
-- Generated: 2026-02-04
-- Rows: 11

INSERT INTO prompt_settings (id, agent_name, section_name, content, description, version, is_active, variant, weight, usage_count, success_count, created_at, updated_at, created_by) VALUES
('3586ad60-a301-4e7f-b9b0-ff37f0d5987b', 'analyst', 'analysis_guidelines', E'Focus on emotional triggers in reviews. Look for specific product/service names that customers mention repeatedly.\n\nRules:\n- Extract CONCRETE examples, not generic praise\n- Look for patterns across multiple reviews\n- Identify what makes customers feel something (trust, excitement, relief)\n- Find the \"before/after\" moments customers describe\n- Note any specific staff names, products, or services mentioned\n- Pay attention to comparisons with competitors', 'Additional guidelines for analyzing business data', 1, true, NULL, 100, 0, 0, '2026-01-11T14:00:57.819Z', '2026-01-11T14:00:57.819Z', NULL),

('5f312bbf-a656-4cdd-83ff-4aafe21034a2', 'concept', 'concept_types', E'- The Heritage: Legacy, tradition, \"Since 1985\", sepia tones, serif fonts\n- The Protector: Safety, shield imagery, heavy industrial type\n- The Maverick: \"We do things differently\", high contrast, unconventional\n- The Scientist: Precision, data-driven, clinical aesthetics\n- The Warm Local: Community-focused, handwritten fonts, cozy vibes\n- The Minimalist Pro: Clean lines, tons of white space, Swiss aesthetic\n- The Bold Disruptor: Neon colors, asymmetric layouts, edgy tone\n- The Timeless Craftsman: Quality materials, detailed work, artisan angle\n- The Modern Tech: Gradients, san-serif, sleek animations\n- The Friendly Expert: Approachable but professional, conversational\n- The Exclusive Club: Premium, members-only feel, gold accents\n- The Adventure Guide: Exploration, discovery, outdoor aesthetics', 'Available brand concept archetypes to choose from', 1, true, NULL, 100, 0, 0, '2026-01-11T14:00:57.819Z', '2026-01-11T14:00:57.819Z', NULL),

('3d02985a-15f3-401d-b7b1-469072ecd9a2', 'art_director', 'frontend_aesthetics', E'Focus on:\n\n**Typography**: Choose fonts that are beautiful, unique, and interesting. Avoid overused AI fonts.\n\n**Color & Theme**: Commit to a cohesive aesthetic. Use CSS variables for theming. Consider light/dark modes when appropriate.\n\n**Motion**: Use animations for scroll effects and micro-interactions. Keep them subtle and purposeful.\n\n**Backgrounds**: Create atmosphere and depth with gradients, textures, or patterns. Avoid plain white unless it''s intentional minimalism.\n\n**Spacing**: Use generous whitespace. Sites should breathe. Mobile-first responsive design.\n\n**Personality**: The design should reflect the brand concept. Every element should support the story.', 'Core design principles and aesthetics guidelines', 1, true, NULL, 100, 0, 0, '2026-01-11T14:00:57.819Z', '2026-01-11T14:00:57.819Z', NULL),

('f0e2dee5-dcfc-4796-887b-3e2fd6387fcf', 'art_director', 'vibe_list', E'- Swiss International: Grid systems, Helvetica-ish precision, huge whitespace, red accents\n- Neo-Brutalism: Hard 3px outlines, raw HTML feel, 90s web nostalgia, loud colors\n- Glassmorphism: Blur effects (backdrop-filter), frosted glass cards, soft pastels\n- Dark Luxury: Deep blacks (#0a0a0a), gold/champagne accents, serif fonts, slow fades\n- Warm Analog: Film grain, warm tones, vintage photography, handwritten touches\n- High-Tech Minimal: Grids, monospace fonts, terminal aesthetics, neon accents\n- Organic Flow: Curved shapes, earth tones, natural textures, soft shadows\n- Bold Maximalist: Clashing colors, overlapping elements, playful chaos, energy\n- Clean Corporate: Professional blue, sans-serif, card layouts, trust signals\n- Retro Future: Synthwave colors, chrome effects, 80s nostalgia, gradients\n- Nordic Minimal: Muted colors, clean lines, functional beauty, simplicity\n- Artisan Craft: Textured backgrounds, serif fonts, detailed illustrations', 'Available design vibe options', 1, true, NULL, 100, 0, 0, '2026-01-11T14:00:57.819Z', '2026-01-11T14:00:57.819Z', NULL),

('9331b116-0cbe-496c-8311-3d27cff9c3e8', 'art_director', 'typography_rules', E'BANNED FONTS (overused, \"AI slop\" indicators):\n- Roboto, Open Sans, Lato, Montserrat, Poppins, Inter\n- Arial, Helvetica (unless Swiss International vibe)\n- Space Grotesk (overused by AI)\n- Comic Sans, Papyrus (obviously)\n\nRECOMMENDED FONT SOURCES:\n- Google Fonts: Look beyond page 1 (sort by \"Trending\")\n- System fonts: -apple-system, BlinkMacSystemFont (great performance)\n- Serif + Sans pairing: Mix warm serif headings with clean sans body\n\nFONT PAIRING RULES:\n- Display font: Bold, distinctive, sets the tone\n- Body font: Highly readable, 16px minimum, good line-height\n- Accent font: Optional - use for buttons, labels, captions\n\nAVOID:\n- Using more than 3 font families\n- Thin fonts (hard to read)\n- All-caps body text\n- Overly decorative fonts for long-form content', 'Typography selection rules and banned fonts', 1, true, NULL, 100, 0, 0, '2026-01-11T14:00:57.819Z', '2026-01-11T14:00:57.819Z', NULL),

('7e6c22ba-436b-4330-a617-13d51ff6efc0', 'concept', 'concept_rules', E'1. Do NOT be generic. \"Quality service\" is not a concept.\n2. The concept must be VISUAL - it should inspire specific design choices.\n3. Consider the local context (Austin TX is different from NYC).\n4. The concept should match the archetype but add unexpected flair.\n5. Avoid clichés - if every competitor could use the same concept, it''s wrong.\n6. The concept should work for a business that has NO existing brand identity.\n7. Think: \"If this were a movie, what genre would it be?\"\n8. The name of the concept should be memorable and ownable.\n9. Think about modern experiences.', 'Rules for creating brand concepts', 1, true, NULL, 100, 0, 0, '2026-01-11T14:00:57.819Z', '2026-01-24T07:35:31.443Z', NULL),

('41e127e4-832b-4d10-97dc-5acfe490552d', 'art_director', 'banned_patterns', E'NEVER USE:\n- Generic stock photos of people in suits shaking hands\n- Vague hero copy like \"Solutions for Your Business\"\n- Hamburger menus on desktop\n- Carousels (users rarely click through)\n- Auto-playing videos with sound\n- Pop-ups before user has scrolled\n- \"Your paragraph text goes here\" placeholder text\n- Lorem ipsum in production\n- Centered body text (hard to read)\n- Tiny text below 14px\n- Low contrast text (fails WCAG)\n- Infinite scrolling with no pagination\n- Fake chat widgets\n- \"As seen on\" logos that are made up\n- Social proof with no real data', 'Design patterns and elements to avoid', 1, true, NULL, 100, 0, 0, '2026-01-11T14:00:57.819Z', '2026-01-11T14:00:57.819Z', NULL),

('20a85318-69f2-4b00-a7a1-459085ecd676', 'architect', 'technical_requirements', E'TECH STACK:\n- Use Tailwind CSS CDN (v3.4+)\n- Use GSAP for animations (from CDN)\n- Vanilla JavaScript (no jQuery)\n- Semantic HTML5 elements\n- CSS Grid and Flexbox for layouts\n- CSS custom properties (variables) for theming\n\nRESPONSIVE DESIGN:\n- Mobile-first approach\n- Breakpoints: sm(640px), md(768px), lg(1024px), xl(1280px)\n- Touch-friendly buttons (min 44px tap targets)\n- Readable font sizes on mobile (16px+ for body)\n\nPERFORMANCE:\n- Lazy load images below the fold\n- Minimize animations on mobile\n- Use CSS animations over JavaScript where possible\n- Optimize for Core Web Vitals\n\nACCESSIBILITY:\n- Proper heading hierarchy (h1, h2, h3)\n- Alt text for all images\n- ARIA labels where needed\n- Keyboard navigation support\n- Sufficient color contrast (WCAG AA minimum)\n\nSEO:\n- Semantic HTML structure\n- Meta tags (title, description, og:image)\n- Schema.org markup for local business\n- Clean, descriptive URLs', 'Technical requirements and constraints for code generation', 1, true, NULL, 100, 0, 0, '2026-01-11T14:00:57.819Z', '2026-01-11T14:00:57.819Z', NULL),

('3ca39dfd-f674-4444-b3a9-354ce7f49191', 'architect', 'section_templates', E'COMMON SECTION PATTERNS:\n\n**Hero Section**:\n- Full-viewport height or 70vh\n- Background image with overlay\n- Headline + subheadline + CTA button\n- Optional: scroll indicator\n\n**About/Services Section**:\n- Grid of 2-3 columns on desktop\n- Cards or feature boxes\n- Icons or images for each item\n- Short, scannable descriptions\n\n**Testimonials**:\n- Cards with quote, name, rating\n- Consider horizontal scroll on mobile\n- Profile photos if available\n- Star ratings (visual)\n\n**CTA Section**:\n- High contrast background\n- Clear action button\n- Urgency or value proposition\n- Optional: contact form\n\n**Footer**:\n- Business info, hours, location\n- Social links (if available)\n- Copyright notice\n- \"Claim This Site\" bar (sticky or fixed bottom)\n\n**Claim Bar Template**:\n```html\n<div class=\"claim-bar\">\n  <p>Is this your business? <a href=\"{{claim_url}}\">Claim this site</a></p>\n</div>\n```', 'HTML/CSS templates for common website sections', 1, true, NULL, 100, 0, 0, '2026-01-11T14:00:57.819Z', '2026-01-11T14:00:57.819Z', NULL),

('3351bfe2-ea58-40ee-a3dc-05fc1d5e60d8', 'art_director', 'industry_style_guidance', E'INDUSTRY-SPECIFIC COLOR PSYCHOLOGY:\n\nWhen industry guidance is provided below, follow it carefully. The recommended colors \nand fonts are based on neuromarketing research showing that specific industries \ntrigger specific psychological responses:\n\n- LEGAL/FINANCE: Navy + Gold = \"My money is safe\" (Heritage & Trust)\n- HEALTHCARE/DENTAL: Teal + White = \"I won''t be hurt here\" (Clinical Precision)\n- PLUMBING/HVAC/AUTO: Red + Yellow = \"Help is coming fast\" (Rapid Response)\n- CONTRACTORS/LANDSCAPING: Green + Orange = \"They''ll build it right\" (Craft & Structure)\n- SALONS/SPAS/EVENTS: Charcoal + Rose = \"I want that lifestyle\" (Aesthetic & Wellness)\n- PETS/EDUCATION/CAFES: Orange + Green = \"The Connection\" (Community & Nurture)\n\nYou can apply creative vibes ON TOP of these industry palettes, but the core \ncolors should align with psychological expectations for conversion optimization.', 'Industry-specific color psychology and typography guidance', 1, true, NULL, 100, 0, 0, '2026-01-23T10:39:29.649Z', '2026-01-23T10:39:29.649Z', NULL),

('1b421dff-580b-4a04-9570-be22e452af55', 'art_director', 'gradient_best_practices', E'GRADIENT ANTI-BANDING (CRITICAL):\n\nCSS gradients often display visible \"bands\" instead of smooth transitions.\nTo prevent this:\n\n1. USE OFF-COLORS: Never pure #FFFFFF or #000000\n   - Use #FAFAFA or #FFFFF0 instead of pure white\n   - Use #0a0a0f or #1a1a1a instead of pure black\n\n2. ADD NOISE OVERLAY: Specify that gradients should include a subtle \n   SVG noise pattern overlay with 5% opacity\n\n3. MULTIPLE COLOR STOPS: Use 3-5 color stops for smooth eased transitions\n   instead of just start/end colors\n\n4. BLUR TECHNIQUE: Large gradient backgrounds can use a pseudo-element \n   with filter: blur(1px) for smoother appearance\n\nWhen specifying colors, always include gradient_start and gradient_end \ncolors that work well together with anti-banding techniques.', 'CSS gradient best practices to prevent color banding', 1, true, NULL, 100, 0, 0, '2026-01-23T10:39:29.649Z', '2026-01-23T10:39:29.649Z', NULL);

